### ISSUE TITLE
RuntimeError: Could not import backend "Pyglet": No standard config is available.

### ISSUE THREAD

**Issue by goddard73** [PhilippAuss/ZS6D#4]
I am trying to reproduce this article, use the command:python3 prepare_templates_and_gt.py --config_file zs6d_configs/template_gt_preparation_configs/cfg_template_gt_generation_ycbv.json

which uses the configs of your project, and I encountered the problem at below:

(zs6d) goddard@GoddardWen:/mnt/d/000Project/ZS6D$ python3 prepare_templates_and_gt.py --config_file zs6d_configs/template_gt_preparation_configs/cfg_template_gt_generation_ycbv.json
Traceback (most recent call last):
  File "/mnt/d/000Project/ZS6D/prepare_templates_and_gt.py", line 8, in <module>
    from rendering.renderer_xyz import Renderer
  File "/mnt/d/000Project/ZS6D/rendering/renderer_xyz.py", line 11, in <module>
    app.use_app('pyglet')   # Set backend
  File "/home/goddard/anaconda3/envs/zs6d/lib/python3.9/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/goddard/anaconda3/envs/zs6d/lib/python3.9/site-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/home/goddard/anaconda3/envs/zs6d/lib/python3.9/site-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
No standard config is available.

Thank you.

**Comment by PhilippAuss** [comment]
I recommend to install pyglet manualy: pip install pyglet==1.2.4
